const API_URL = 'https://norma.nomoreparties.space/api'
const HEIGHT_OF_CONSTRUCTOR_ITEM = 80;
const CONSTRUCTOR_MARGIN = 8;

const ADD_CHOSEN_INGREDIENT = 'ADD_CHOSEN_INGREDIENT';
const REMOVE_CHOSEN_INGREDIENT = 'REMOVE_CHOSEN_INGREDIENT'


export {
  API_URL,
  HEIGHT_OF_CONSTRUCTOR_ITEM,
  CONSTRUCTOR_MARGIN,
  ADD_CHOSEN_INGREDIENT,
  REMOVE_CHOSEN_INGREDIENT,
}

