const API_URL = 'https://norma.nomoreparties.space/api'
const HEIGHT_OF_CONSTRUCTOR_ITEM = 80;
const CONSTRUCTOR_MARGIN = 8;

const ADD_CHOSEN_INGREDIENT = 'ADD_CHOSEN_INGREDIENT';
const ADD_CHOSEN_BUN = 'ADD_CHOSEN_BUN';
const REMOVE_CHOSEN_INGREDIENT = 'REMOVE_CHOSEN_INGREDIENT';
const REQUEST_INGREDIENTS_SUCCESS = 'REQUEST_INGREDIENTS_SUCCESS';
const REQUEST_INGREDIENTS_FAILED = 'REQUEST_INGREDIENTS_FAILED';
const POST_ORDER_SUCCESS = 'POST_ORDER_SUCCESS';
const POST_ORDER_FAILED = 'POST_ORDER_FAILED';
const CHANGE_INGREDIENTS_TAB = 'CHANGE_INGREDIENTS_TAB';
const SET_ACTIVE_INGREDIENT = 'SET_ACTIVE_INGREDIENT';
const RESET_ACTIVE_INGREDIENT = 'RESET_ACTIVE_INGREDIENT';
const RESET_CURRENT_ORDER = 'RESET_CURRENT_ORDER';
const ELEMENT_SORTED_BY_DND = 'ELEMENT_SORTED_BY_DND';
const API_REQUEST_IN_PROGRESS = 'API_REQUEST_IN_PROGRESS';
const API_REQUEST_FINISHED = 'API_REQUEST_FINISHED';

export {
  API_URL,
  HEIGHT_OF_CONSTRUCTOR_ITEM,
  CONSTRUCTOR_MARGIN,
  ADD_CHOSEN_INGREDIENT,
  ADD_CHOSEN_BUN,
  REMOVE_CHOSEN_INGREDIENT,
  REQUEST_INGREDIENTS_SUCCESS,
  REQUEST_INGREDIENTS_FAILED,
  CHANGE_INGREDIENTS_TAB,
  SET_ACTIVE_INGREDIENT,
  RESET_ACTIVE_INGREDIENT,
  POST_ORDER_SUCCESS,
  POST_ORDER_FAILED,
  RESET_CURRENT_ORDER,
  ELEMENT_SORTED_BY_DND,
  API_REQUEST_IN_PROGRESS,
  API_REQUEST_FINISHED,
}
