const API_URL = 'https://norma.nomoreparties.space/api'
const HEIGHT_OF_CONSTRUCTOR_ITEM = 80;
const CONSTRUCTOR_MARGIN = 8;

const ADD_CHOSEN_INGREDIENT = 'ADD_CHOSEN_INGREDIENT';
const REMOVE_CHOSEN_INGREDIENT = 'REMOVE_CHOSEN_INGREDIENT';
const REQUEST_INGREDIENTS_SUCCESS = 'REQUEST_INGREDIENTS_SUCCESS';
const REQUEST_INGREDIENTS_FAILED = 'REQUEST_INGREDIENTS_FAILED';
const CHANGE_INGREDIENTS_TAB = 'CHANGE_INGREDIENTS_TAB';
const SET_ACTIVE_INGREDIENT = 'SET_ACTIVE_INGREDIENT'
const RESET_ACTIVE_INGREDIENT = 'RESET_ACTIVE_INGREDIENT'


export {
  API_URL,
  HEIGHT_OF_CONSTRUCTOR_ITEM,
  CONSTRUCTOR_MARGIN,
  ADD_CHOSEN_INGREDIENT,
  REMOVE_CHOSEN_INGREDIENT,
  REQUEST_INGREDIENTS_SUCCESS,
  REQUEST_INGREDIENTS_FAILED,
  CHANGE_INGREDIENTS_TAB,
  SET_ACTIVE_INGREDIENT,
  RESET_ACTIVE_INGREDIENT,
  
}

