import { IN_PROGRESS, COMPLETED } from './constants';

export const orders = [
  {
    name: 'Space антарианский флюоресцентный бургер',
    _id: '60b920b9f26f8awrg027e0a02d',
    status: IN_PROGRESS,
    order: {
      number: 459333,
      cost: 430,
      orderedAt: new Date(2021, 5, 2, 11, 44),
      ingredients: [
        {
          _id: '60b920b9f26f8a0027e0a02d',
          name: 'Краторная булка N-200i',
          type: 'bun',
          proteins: 80,
          fat: 24,
          carbohydrates: 53,
          calories: 420,
          price: 1255,
          image: 'https://code.s3.yandex.net/react/code/bun-02.png',
          image_mobile: 'https://code.s3.yandex.net/react/code/bun-02-mobile.png',
          image_large: 'https://code.s3.yandex.net/react/code/bun-02-large.png',
          __v: 0,
        },
        {
          _id: '60b920b9f26f8a0027e0a039',
          name: 'Кристаллы марсианских альфа-сахаридов',
          type: 'main',
          proteins: 234,
          fat: 432,
          carbohydrates: 111,
          calories: 189,
          price: 762,
          image: 'https://code.s3.yandex.net/react/code/core.png',
          image_mobile: 'https://code.s3.yandex.net/react/code/core-mobile.png',
          image_large: 'https://code.s3.yandex.net/react/code/core-large.png',
          __v: 0,
        },
        {
          _id: '60b920b9f26f8a0027e0a039',
          name: 'Кристаллы марсианских альфа-сахаридов',
          type: 'main',
          proteins: 234,
          fat: 432,
          carbohydrates: 111,
          calories: 189,
          price: 762,
          image: 'https://code.s3.yandex.net/react/code/core.png',
          image_mobile: 'https://code.s3.yandex.net/react/code/core-mobile.png',
          image_large: 'https://code.s3.yandex.net/react/code/core-large.png',
          __v: 0,
        },
        {
          _id: '60b920b9f26f8a0027e0a039',
          name: 'Кристаллы марсианских альфа-сахаридов',
          type: 'main',
          proteins: 234,
          fat: 432,
          carbohydrates: 111,
          calories: 189,
          price: 762,
          image: 'https://code.s3.yandex.net/react/code/core.png',
          image_mobile: 'https://code.s3.yandex.net/react/code/core-mobile.png',
          image_large: 'https://code.s3.yandex.net/react/code/core-large.png',
          __v: 0,
        },
        {
          _id: '60b920b9f26f8a0027e0a03a',
          name: 'Мини-салат Экзо-Плантаго',
          type: 'main',
          proteins: 1,
          fat: 2,
          carbohydrates: 3,
          calories: 6,
          price: 4400,
          image: 'https://code.s3.yandex.net/react/code/salad.png',
          image_mobile: 'https://code.s3.yandex.net/react/code/salad-mobile.png',
          image_large: 'https://code.s3.yandex.net/react/code/salad-large.png',
          __v: 0,
        },
        {
          _id: '60b920b9f26f8a0027e0a03b',
          name: 'Сыр с астероидной плесенью',
          type: 'main',
          proteins: 84,
          fat: 48,
          carbohydrates: 420,
          calories: 3377,
          price: 4142,
          image: 'https://code.s3.yandex.net/react/code/cheese.png',
          image_mobile: 'https://code.s3.yandex.net/react/code/cheese-mobile.png',
          image_large: 'https://code.s3.yandex.net/react/code/cheese-large.png',
          __v: 0,
        },
      ],
    },
  },
  {
    name: 'Бессмертный space краторный бургер',
    _id: '60b920b9f26f8a0027e0a02d',
    status: IN_PROGRESS,
    order: {
      number: 84570,
      cost: 8081,
      orderedAt: new Date(2021, 5, 4, 12, 59),
      ingredients: [
        {
          _id: '60b920b9f26f8a0027e0a02d',
          name: 'Краторная булка N-200i',
          type: 'bun',
          proteins: 80,
          fat: 24,
          carbohydrates: 53,
          calories: 420,
          price: 1255,
          image: 'https://code.s3.yandex.net/react/code/bun-02.png',
          image_mobile: 'https://code.s3.yandex.net/react/code/bun-02-mobile.png',
          image_large: 'https://code.s3.yandex.net/react/code/bun-02-large.png',
          __v: 0,
        },
        {
          _id: '60b920b9f26f8a0027e0a036',
          name: 'Соус с шипами Антарианского плоскоходца',
          type: 'sauce',
          proteins: 101,
          fat: 99,
          carbohydrates: 100,
          calories: 100,
          price: 88,
          image: 'https://code.s3.yandex.net/react/code/sauce-01.png',
          image_mobile: 'https://code.s3.yandex.net/react/code/sauce-01-mobile.png',
          image_large: 'https://code.s3.yandex.net/react/code/sauce-01-large.png',
          __v: 0,
        },
        {
          _id: '60b920b9f26f8a0027e0a037',
          name: 'Хрустящие минеральные кольца',
          type: 'main',
          proteins: 808,
          fat: 689,
          carbohydrates: 609,
          calories: 986,
          price: 300,
          image: 'https://code.s3.yandex.net/react/code/mineral_rings.png',
          image_mobile: 'https://code.s3.yandex.net/react/code/mineral_rings-mobile.png',
          image_large: 'https://code.s3.yandex.net/react/code/mineral_rings-large.png',
          __v: 0,
        },
        {
          _id: '60b920b9f26f8a0027e0a038',
          name: 'Плоды Фалленианского дерева',
          type: 'main',
          proteins: 20,
          fat: 5,
          carbohydrates: 55,
          calories: 77,
          price: 874,
          image: 'https://code.s3.yandex.net/react/code/sp_1.png',
          image_mobile: 'https://code.s3.yandex.net/react/code/sp_1-mobile.png',
          image_large: 'https://code.s3.yandex.net/react/code/sp_1-large.png',
          __v: 0,
        },
        {
          _id: '60b920b9f26f8a0027e0a036',
          name: 'Соус с шипами Антарианского плоскоходца',
          type: 'sauce',
          proteins: 101,
          fat: 99,
          carbohydrates: 100,
          calories: 100,
          price: 88,
          image: 'https://code.s3.yandex.net/react/code/sauce-01.png',
          image_mobile: 'https://code.s3.yandex.net/react/code/sauce-01-mobile.png',
          image_large: 'https://code.s3.yandex.net/react/code/sauce-01-large.png',
          __v: 0,
        },
        {
          _id: '60b920b9f26f8a0027e0a037',
          name: 'Хрустящие минеральные кольца',
          type: 'main',
          proteins: 808,
          fat: 689,
          carbohydrates: 609,
          calories: 986,
          price: 300,
          image: 'https://code.s3.yandex.net/react/code/mineral_rings.png',
          image_mobile: 'https://code.s3.yandex.net/react/code/mineral_rings-mobile.png',
          image_large: 'https://code.s3.yandex.net/react/code/mineral_rings-large.png',
          __v: 0,
        },
        {
          _id: '60b920b9f26f8a0027e0a038',
          name: 'Плоды Фалленианского дерева',
          type: 'main',
          proteins: 20,
          fat: 5,
          carbohydrates: 55,
          calories: 77,
          price: 874,
          image: 'https://code.s3.yandex.net/react/code/sp_1.png',
          image_mobile: 'https://code.s3.yandex.net/react/code/sp_1-mobile.png',
          image_large: 'https://code.s3.yandex.net/react/code/sp_1-large.png',
          __v: 0,
        },
        {
          _id: '60b920b9f26f8a0027e0a039',
          name: 'Кристаллы марсианских альфа-сахаридов',
          type: 'main',
          proteins: 234,
          fat: 432,
          carbohydrates: 111,
          calories: 189,
          price: 762,
          image: 'https://code.s3.yandex.net/react/code/core.png',
          image_mobile: 'https://code.s3.yandex.net/react/code/core-mobile.png',
          image_large: 'https://code.s3.yandex.net/react/code/core-large.png',
          __v: 0,
        },
        {
          _id: '60b920b9f26f8a0027e0a039',
          name: 'Кристаллы марсианских альфа-сахаридов',
          type: 'main',
          proteins: 234,
          fat: 432,
          carbohydrates: 111,
          calories: 189,
          price: 762,
          image: 'https://code.s3.yandex.net/react/code/core.png',
          image_mobile: 'https://code.s3.yandex.net/react/code/core-mobile.png',
          image_large: 'https://code.s3.yandex.net/react/code/core-large.png',
          __v: 0,
        },
        {
          _id: '60b920b9f26f8a0027e0a03a',
          name: 'Мини-салат Экзо-Плантаго',
          type: 'main',
          proteins: 1,
          fat: 2,
          carbohydrates: 3,
          calories: 6,
          price: 4400,
          image: 'https://code.s3.yandex.net/react/code/salad.png',
          image_mobile: 'https://code.s3.yandex.net/react/code/salad-mobile.png',
          image_large: 'https://code.s3.yandex.net/react/code/salad-large.png',
          __v: 0,
        },
        {
          _id: '60b920b9f26f8a0027e0a03b',
          name: 'Сыр с астероидной плесенью',
          type: 'main',
          proteins: 84,
          fat: 48,
          carbohydrates: 420,
          calories: 3377,
          price: 4142,
          image: 'https://code.s3.yandex.net/react/code/cheese.png',
          image_mobile: 'https://code.s3.yandex.net/react/code/cheese-mobile.png',
          image_large: 'https://code.s3.yandex.net/react/code/cheese-large.png',
          __v: 0,
        },
      ],
    },
  },
  {
    name: 'Фалленианский астероидный краторный минеральный бургер',
    _id: '60b920b9f26f8a0027erfui4',
    status: COMPLETED,
    order: {
      number: 91276,
      cost: 2033,
      orderedAt: new Date(2021, 5, 5, 12, 59),
      ingredients: [
        {
          _id: '60b920b9f26f8a0027e0a02d',
          name: 'Краторная булка N-200i',
          type: 'bun',
          proteins: 80,
          fat: 24,
          carbohydrates: 53,
          calories: 420,
          price: 1255,
          image: 'https://code.s3.yandex.net/react/code/bun-02.png',
          image_mobile: 'https://code.s3.yandex.net/react/code/bun-02-mobile.png',
          image_large: 'https://code.s3.yandex.net/react/code/bun-02-large.png',
          __v: 0,
        },
        {
          _id: '60b920b9f26f8a0027e0a030',
          name: 'Мясо бессмертных моллюсков Protostomia',
          type: 'main',
          proteins: 433,
          fat: 244,
          carbohydrates: 33,
          calories: 420,
          price: 1337,
          image: 'https://code.s3.yandex.net/react/code/meat-02.png',
          image_mobile: 'https://code.s3.yandex.net/react/code/meat-02-mobile.png',
          image_large: 'https://code.s3.yandex.net/react/code/meat-02-large.png',
          __v: 0,
        },
        {
          _id: '60b920b9f26f8a0027e0a030',
          name: 'Мясо бессмертных моллюсков Protostomia',
          type: 'main',
          proteins: 433,
          fat: 244,
          carbohydrates: 33,
          calories: 420,
          price: 1337,
          image: 'https://code.s3.yandex.net/react/code/meat-02.png',
          image_mobile: 'https://code.s3.yandex.net/react/code/meat-02-mobile.png',
          image_large: 'https://code.s3.yandex.net/react/code/meat-02-large.png',
          __v: 0,
        },
        {
          _id: '60b920b1116f8a0027e0a035',
          name: 'Соус традиционный галактический',
          type: 'sauce',
          proteins: 42,
          fat: 24,
          carbohydrates: 42,
          calories: 99,
          price: 15,
          image: 'https://code.s3.yandex.net/react/code/sauce-03.png',
          image_mobile: 'https://code.s3.yandex.net/react/code/sauce-03-mobile.png',
          image_large: 'https://code.s3.yandex.net/react/code/sauce-03-large.png',
          __v: 0,
        },
      ],
    },
  },
  {
    name: 'Space антарианский флюоресцентный бургер',
    _id: '60b920bzf26f8awrg027e0a02d',
    status: COMPLETED,
    order: {
      number: 4503,
      cost: 430,
      orderedAt: new Date(2020, 5, 5, 3, 15),
      ingredients: [
        {
          _id: '60b920b9f26f8a0027e0a02d',
          name: 'Краторная булка N-200i',
          type: 'bun',
          proteins: 80,
          fat: 24,
          carbohydrates: 53,
          calories: 420,
          price: 1255,
          image: 'https://code.s3.yandex.net/react/code/bun-02.png',
          image_mobile: 'https://code.s3.yandex.net/react/code/bun-02-mobile.png',
          image_large: 'https://code.s3.yandex.net/react/code/bun-02-large.png',
          __v: 0,
        },
        {
          _id: '60b920b9f26f8a0027e0a039',
          name: 'Кристаллы марсианских альфа-сахаридов',
          type: 'main',
          proteins: 234,
          fat: 432,
          carbohydrates: 111,
          calories: 189,
          price: 762,
          image: 'https://code.s3.yandex.net/react/code/core.png',
          image_mobile: 'https://code.s3.yandex.net/react/code/core-mobile.png',
          image_large: 'https://code.s3.yandex.net/react/code/core-large.png',
          __v: 0,
        },
        {
          _id: '60b920b9f26f8a0027e0a03a',
          name: 'Мини-салат Экзо-Плантаго',
          type: 'main',
          proteins: 1,
          fat: 2,
          carbohydrates: 3,
          calories: 6,
          price: 4400,
          image: 'https://code.s3.yandex.net/react/code/salad.png',
          image_mobile: 'https://code.s3.yandex.net/react/code/salad-mobile.png',
          image_large: 'https://code.s3.yandex.net/react/code/salad-large.png',
          __v: 0,
        },
        {
          _id: '60b920b9f26f8a0027e0a03b',
          name: 'Сыр с астероидной плесенью',
          type: 'main',
          proteins: 84,
          fat: 48,
          carbohydrates: 420,
          calories: 3377,
          price: 4142,
          image: 'https://code.s3.yandex.net/react/code/cheese.png',
          image_mobile: 'https://code.s3.yandex.net/react/code/cheese-mobile.png',
          image_large: 'https://code.s3.yandex.net/react/code/cheese-large.png',
          __v: 0,
        },
      ],
    },
  },
  {
    name: 'Бессмертный space краторный бургер',
    _id: '60b920b9f26f8a0027e0a02das',
    status: COMPLETED,
    order: {
      number: 457,
      cost: 8081,
      orderedAt: new Date(2021, 10, 3, 2, 33),
      ingredients: [
        {
          _id: '60b920b9f26f8a0027e0a02d',
          name: 'Краторная булка N-200i',
          type: 'bun',
          proteins: 80,
          fat: 24,
          carbohydrates: 53,
          calories: 420,
          price: 1255,
          image: 'https://code.s3.yandex.net/react/code/bun-02.png',
          image_mobile: 'https://code.s3.yandex.net/react/code/bun-02-mobile.png',
          image_large: 'https://code.s3.yandex.net/react/code/bun-02-large.png',
          __v: 0,
        },
        {
          _id: '60b920b9f26f8a0027e0a036',
          name: 'Соус с шипами Антарианского плоскоходца',
          type: 'sauce',
          proteins: 101,
          fat: 99,
          carbohydrates: 100,
          calories: 100,
          price: 88,
          image: 'https://code.s3.yandex.net/react/code/sauce-01.png',
          image_mobile: 'https://code.s3.yandex.net/react/code/sauce-01-mobile.png',
          image_large: 'https://code.s3.yandex.net/react/code/sauce-01-large.png',
          __v: 0,
        },
        {
          _id: '60b920b9f26f8a0027e0a037',
          name: 'Хрустящие минеральные кольца',
          type: 'main',
          proteins: 808,
          fat: 689,
          carbohydrates: 609,
          calories: 986,
          price: 300,
          image: 'https://code.s3.yandex.net/react/code/mineral_rings.png',
          image_mobile: 'https://code.s3.yandex.net/react/code/mineral_rings-mobile.png',
          image_large: 'https://code.s3.yandex.net/react/code/mineral_rings-large.png',
          __v: 0,
        },
        {
          _id: '60b920b9f26f8a0027e0a038',
          name: 'Плоды Фалленианского дерева',
          type: 'main',
          proteins: 20,
          fat: 5,
          carbohydrates: 55,
          calories: 77,
          price: 874,
          image: 'https://code.s3.yandex.net/react/code/sp_1.png',
          image_mobile: 'https://code.s3.yandex.net/react/code/sp_1-mobile.png',
          image_large: 'https://code.s3.yandex.net/react/code/sp_1-large.png',
          __v: 0,
        },
      ],
    },
  },
  {
    name: 'Фалленианский астероидный краторный минеральный бургер',
    _id: 'web920b9f26f8a0027erfui4',
    status: COMPLETED,
    order: {
      number: 61276,
      cost: 55421,
      orderedAt: new Date(2021, 2, 1, 0, 15),
      ingredients: [
        {
          _id: '60b920b9f26f8a0027e0a02d',
          name: 'Краторная булка N-200i',
          type: 'bun',
          proteins: 80,
          fat: 24,
          carbohydrates: 53,
          calories: 420,
          price: 1255,
          image: 'https://code.s3.yandex.net/react/code/bun-02.png',
          image_mobile: 'https://code.s3.yandex.net/react/code/bun-02-mobile.png',
          image_large: 'https://code.s3.yandex.net/react/code/bun-02-large.png',
          __v: 0,
        },
        {
          _id: '60b920b9f26f8a0027e0a030',
          name: 'Мясо бессмертных моллюсков Protostomia',
          type: 'main',
          proteins: 433,
          fat: 244,
          carbohydrates: 33,
          calories: 420,
          price: 1337,
          image: 'https://code.s3.yandex.net/react/code/meat-02.png',
          image_mobile: 'https://code.s3.yandex.net/react/code/meat-02-mobile.png',
          image_large: 'https://code.s3.yandex.net/react/code/meat-02-large.png',
          __v: 0,
        },
        {
          _id: '60b920b9f26f8a0027e0a030',
          name: 'Мясо бессмертных моллюсков Protostomia',
          type: 'main',
          proteins: 433,
          fat: 244,
          carbohydrates: 33,
          calories: 420,
          price: 1337,
          image: 'https://code.s3.yandex.net/react/code/meat-02.png',
          image_mobile: 'https://code.s3.yandex.net/react/code/meat-02-mobile.png',
          image_large: 'https://code.s3.yandex.net/react/code/meat-02-large.png',
          __v: 0,
        },
        {
          _id: '60b920b9f26f8a0027e0a035',
          name: 'Соус традиционный галактический',
          type: 'sauce',
          proteins: 42,
          fat: 24,
          carbohydrates: 42,
          calories: 99,
          price: 15,
          image: 'https://code.s3.yandex.net/react/code/sauce-03.png',
          image_mobile: 'https://code.s3.yandex.net/react/code/sauce-03-mobile.png',
          image_large: 'https://code.s3.yandex.net/react/code/sauce-03-large.png',
          __v: 0,
        },
      ],
    },
  },

];
