export const WS_INIT: 'WS_INIT' ='WS_INIT';
export const WS_AUTH_INIT: 'WS_AUTH_INIT' ='WS_AUTH_INIT';
export const WS_SEND_MESSAGE: 'WS_SEND_MESSAGE' ='WS_SEND_MESSAGE';
export const WS_SEND_AUTH_MESSAGE: 'WS_SEND_AUTH_MESSAGE' ='WS_SEND_AUTH_MESSAGE';
